name = "kei3"
compatibility_date = "2025-07-21"

routes = [
  { pattern = "kei3.japanfinance.org", custom_domain = true }
]

preview_urls = true

[assets]
directory = "./dist/"
not_found_handling = "404-page"
